{% set name = "napari-sim-processor" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-sim-processor-{{ version }}.tar.gz
  sha256: b055e7cfe336bd2b0e1ba409513190ebb62fbc5d34f746a14e311a8f7dd3779f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pandas  # Imported but not listed in requirements
    - python >={{ python_min }}
    - qtpy
    # - scikit-image  # Listed in requirements but not imported
    - scipy  # Imported but not listed in requirements
    - superqt >=0.3.2

test:
  imports:
    - napari_sim_processor
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/andreabassi78/napari-sim-processor
  summary: A napari widget to process Structured Illumination Microscopy data with gpu acceleration
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/andreabassi78/napari-sim-processor

extra:
  recipe-maintainers:
    - andreabassi78
    - goanpeca
    - jaimergp
